version: "3.9"

services:
  dev-db:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    volumes:
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
